### ISSUE TITLE
Windows开发环境搭建（简化版）

### ISSUE THREAD

**Issue by imygg** [imygg/laravel-essential-training-5.5-Notes#3]
# Windows开发环境搭建

> Windows 下，~ 目录代表着 C:\Users\你的用户名。

## 所需软件下载

[大部份所需软件 百度网盘下载](https://pan.baidu.com/s/1jH6o5sa)

## 安装编辑器 Atom

添加环境变量：

我的电脑 > 属性 > 高级系统设置 > 环境变量 > 修改用户变量或系统变量中的 Path > 新建 > 添加变量地址，如 `C:\Atom` > 一路确定，重启计算机。

测试：`atom --version`

## 安装 Git

无需另行安装。

检测：`git --version`

## 安装虚拟机盒子 Homestead Box

[国内定制版本 Homestead Box](http://106.187.35.107/lt-homestead-3-0-0-2017082400.zip)

解压到非中文路径，运行以下命令导入 Box：

`vagrant box add metadata.json`

使用 Git 下载定制版的 Homestead：

```
cd ~
git clone https://git.coding.net/summerblue/homestead.git Homestead
```

检出我们需要的 Homestead 版本：

```
cd ~/Homestead
git checkout v5.4.0
```

初始化 Homestead：

`bash init.sh`

## 配置 Homestead.yaml 文件

Homestead.yaml 文件在 ~/Homestead 文件夹里。

```
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa
    - ~/.ssh/id_rsa.pub

folders:
    - map: ~/Code
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/Code/Laravel/public

databases:
    - homestead
```

生成 SSH Key，将 your_email@example.com 替换为你的邮箱：

`ssh-keygen -t rsa -C "your_email@example.com"`

一路 Enter 键即可。

创建~/Code 文件夹：

```
cd ~
mkdir Code
```

绑定 hosts：

使用编辑器直接打开文件： C:\Windows\System32\Drivers\etc\hosts ，在最后面加入以下一行：

`192.168.10.10  homestead.app`

## 运行 Vagrant

启动 Homestead：

`cd ~/Homestead && vagrant up`

登录 Homestead 虚拟机：

`vagrant ssh`

退出虚拟机：

`exit`

关闭 Homestead：

`vagrant halt`
